### PR TITLE
Update to version 2020.1

### LINKED ISSUE #8: [INFO] 2020.1 released
New GPG Suite version 2020.1 has been released on 8 June 2020:

https://gpgtools.org/releases/gpgsuite/2020.1/release-notes.html

Source code: https://releases.gpgtools.org/GPG_Suite-2020.1.txz

EDIT – source code apparently available on GitHub too: https://github.com/GPGTools/Libmacgpg

### PR DESCRIPTION
**Pull request by bnavigator**
Hi,

I downloaded the released source code and applied it to the repository.

I do not own a Mac and cannot test the result, but I have co-workers who would benefit from an update.

Could someone please compile and check if this works or check by using the attached library, which was compiled using github workflows in [my forked repository](https://github.com/bnavigator/libmacgpg-free/actions/runs/139889026)? -- 
[org.gpgtools.Libmacgpg.zip](https://github.com/macgpg/libmacgpg-free/files/4799894/org.gpgtools.Libmacgpg.zip)

If successful: Fixes #8

### CODE REVIEW

**Comment by bnavigator** [comment]
In reply to https://github.com/macgpg/libmacgpg-free/issues/8#issuecomment-646193933
> For me at least it doesn't seem to work.

@chiffon-rouge Could you please elaborate? 

Do you get any error messages? Does the GPG plugin in Apple Mail not load? Is the trial period check not gone?

**Comment by ghost** [comment]
I'm sorry, my reply was pretty brief I guess. I used the compiled library, which doesn't change anything if used. I still have the "decrypt only" respectively trail version of GPG Mail. I reinstalled GPG Suite for testing and I have followed all instructions, including restarting.

**Comment by MKesenheimer** [comment]
> I'm sorry, my reply was pretty brief I guess. I used the compiled library, which doesn't change anything if used. I still have the "decrypt only" respectively trail version of GPG Mail. I reinstalled GPG Suite for testing and I have followed all instructions, including restarting.

This is exactly what I did, and I get the same result. I followed the instructions on the main site and restarted the service and my computer.
Still "Decrypt only - Trial expired".

**Edit**
I build your source and copied `org.gpgtools.Libmacgpg` to the destination, as explained. Still trial version.

**Comment by bnavigator** [comment]
GPG Mail modified the DRM code for 2019.2 and later. More modifications than just the library are necessary now. Try https://github.com/GpgMailNoActivation/GpgMailNoActivation/pull/7.

**Pull request closed without merging**
